services:
    ServiceBus.handler:
        class: ServiceBus\ServiceBusHandlerResolver
        public: false

    ServiceBus.mediator:
        class: ServiceBus\Mediator
        arguments: 
            [@ServiceBus.handler]